name: urunan
description: Urunan App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  auto_route: ^8.2.0
  auto_route_generator: ^8.0.0
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  camera: ^0.11.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
