// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///
/// Environment.
enum Environment {
  /// Development.
  development,

  /// Staging.
  staging,

  /// Production.
  production,
}

class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(Environment env) {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaufbCgFMSKDgG7U-u7l23g3l8PPL_1bo',
    appId: '1:887751415351:android:e474141cb5bf3b024e11b2',
    messagingSenderId: '887751415351',
    projectId: 'cheapedin-demo',
    storageBucket: 'cheapedin-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehbJO6urJN3K8qjnbOg7icNLXWlt7F3Q',
    appId: '1:887751415351:ios:76cc5db53b9961f74e11b2',
    messagingSenderId: '887751415351',
    projectId: 'cheapedin-demo',
    storageBucket: 'cheapedin-demo.appspot.com',
    iosClientId:
        '887751415351-ajufr9rfqoakr0ui0jib92f1gfqak2qe.apps.googleusercontent.com',
    iosBundleId: 'com.eternalenterprise.urunan',
  );
}
